"""Research Brief domain rules and API serialization.

The brief is the explicit handoff contract between topic exploration and the
survey writer.  It remains structured throughout the pipeline so research
questions and scope boundaries are auditable instead of being flattened into
an opaque prompt string.
"""

from __future__ import annotations

from typing import Any

LIST_FIELDS = (
    "section_hints",
    "doc_keywords",
    "research_questions",
    "inclusion_criteria",
    "exclusion_criteria",
    "evidence_gaps",
    "doc_scope",
)
TEXT_FIELDS = ("topic", "summary", "readiness_reason")


def _clean_list(value: Any, *, limit: int = 30) -> list[str]:
    if not isinstance(value, list):
        return []
    return list(dict.fromkeys(
        text
        for item in value
        if (text := str(item).strip())
    ))[:limit]


def normalize_brief(raw: dict[str, Any]) -> dict[str, Any]:
    normalized: dict[str, Any] = {
        field: str(raw.get(field, "") or "").strip()
        for field in TEXT_FIELDS
    }
    for field in LIST_FIELDS:
        normalized[field] = _clean_list(raw.get(field))
    normalized["readiness_score"] = max(
        0, min(100, int(raw.get("readiness_score", 0) or 0))
    )
    normalized["evidence_documents"] = max(
        0, int(raw.get("evidence_documents", 0) or 0)
    )
    normalized["search_rounds"] = max(
        0, int(raw.get("search_rounds", 0) or 0)
    )
    return normalized


def merge_brief(
    current: dict[str, Any],
    patch: dict[str, Any],
) -> dict[str, Any]:
    merged = {**current}
    for field in (*TEXT_FIELDS, *LIST_FIELDS, "readiness_score"):
        if field in patch and patch[field] is not None:
            merged[field] = patch[field]
    # Evidence counters and document scope are generated by retrieval and are
    # deliberately not editable through the general brief editor.
    merged["evidence_documents"] = current.get("evidence_documents", 0)
    merged["search_rounds"] = current.get("search_rounds", 0)
    merged["doc_scope"] = current.get("doc_scope", [])
    return normalize_brief(merged)


def validation_errors(brief: dict[str, Any]) -> list[str]:
    errors: list[str] = []
    if len(str(brief.get("topic", "")).strip()) < 6:
        errors.append("综述主题过短")
    questions = _clean_list(brief.get("research_questions"))
    if len(questions) < 2:
        errors.append("至少需要 2 个核心研究问题")
    if not _clean_list(brief.get("inclusion_criteria")):
        errors.append("至少需要 1 条纳入边界")
    return errors


def to_context(brief: dict[str, Any]) -> str:
    parts = [
        f"选题讨论结论：{brief.get('summary', '')}",
        "核心研究问题：" + "；".join(brief.get("research_questions", [])),
        "章节线索：" + "；".join(brief.get("section_hints", [])),
        "纳入边界：" + "；".join(brief.get("inclusion_criteria", [])),
    ]
    if brief.get("exclusion_criteria"):
        parts.append("排除范围：" + "；".join(brief["exclusion_criteria"]))
    if brief.get("evidence_gaps"):
        parts.append("已知证据缺口：" + "；".join(brief["evidence_gaps"]))
    parts.append(
        f"选题成熟度：{brief.get('readiness_score', 0)}/100"
        f"（{brief.get('readiness_reason', '')}）"
    )
    return "\n".join(part for part in parts if part.rstrip("："))


def response(record: dict[str, Any]) -> dict[str, Any]:
    return {
        **record["brief"],
        "brief_id": record["id"],
        "conv_id": record["conv_id"],
        "version": record["version"],
        "status": record["status"],
        "task_id": record.get("task_id", ""),
        "created_at": record["created_at"],
        "updated_at": record["updated_at"],
        "confirmed_at": record.get("confirmed_at"),
        "handed_off_at": record.get("handed_off_at"),
    }
